"use strict";
exports.__esModule = true;
var FIRST_COLOR = '#ffeece';
var SECOND_COLOR = '#cf7249';
var startingTable = [
    { figure: -6, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: -5, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -4, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: -3, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -2, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: -4, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -5, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: -6, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: -1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: -1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: -1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: -1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 0, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 0, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 1, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 1, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 6, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 5, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 4, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 3, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 2, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 4, squareColor: FIRST_COLOR, possibleTurn: false },
    { figure: 5, squareColor: SECOND_COLOR, possibleTurn: false },
    { figure: 6, squareColor: FIRST_COLOR, possibleTurn: false },
];
exports.startingTable = startingTable;
